name: Deploy to GitHub Pages

on:
push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: actions/checkout@v2

  - name: Inject Firebase Config
    run: |
      # Firebase-Konfigurationswerte aus den Secrets laden
      FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}"
      FIREBASE_AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}"
      FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
      FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}"
      FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
      FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}"

      # Original-HTML-Datei lesen
      HTML_CONTENT=$(cat chat_app.html)

      # Platzhalter in der HTML-Datei ersetzen
      UPDATED_HTML_CONTENT="${HTML_CONTENT/\"\${FIREBASE_API_KEY}\"/\"$FIREBASE_API_KEY\"}"
      UPDATED_HTML_CONTENT="${UPDATED_HTML_CONTENT/\"\${FIREBASE_AUTH_DOMAIN}\"/\"$FIREBASE_AUTH_DOMAIN\"}"
      UPDATED_HTML_CONTENT="${UPDATED_HTML_CONTENT/\"\${FIREBASE_PROJECT_ID}\"/\"$FIREBASE_PROJECT_ID\"}"
      UPDATED_HTML_CONTENT="${UPDATED_HTML_CONTENT/\"\${FIREBASE_STORAGE_BUCKET}\"/\"$FIREBASE_STORAGE_BUCKET\"}"
      UPDATED_HTML_CONTENT="${UPDATED_HTML_CONTENT/\"\${FIREBASE_MESSAGING_SENDER_ID}\"/\"$FIREBASE_MESSAGING_SENDER_ID\"}"
      UPDATED_HTML_CONTENT="${UPDATED_HTML_CONTENT/\"\${FIREBASE_APP_ID}\"/\"$FIREBASE_APP_ID\"}"

      # Aktualisierten Inhalt in die Datei zurückschreiben
      echo "$UPDATED_HTML_CONTENT" > chat_app.html

  - name: Rename to index.html
    run: mv chat_app.html index.html
      
  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: .
